spring:
  datasource:
    url: jdbc:mysql://umc4th-database.cjehwko6l8cy.us-east-2.rds.amazonaws.com:3306/umc4th?userSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&autoReconnect=True
    username : admin
    password : doxmf8553!
    driver-class-name: com.mysql.cj.jdbc.Driver